"""Comprehensive VM tree integration tests.

Walks every node in spec/viewmodels.md §2 and asserts:
  1. Existence — class importable from guidearch.viewmodels
  2. Construction — VM uses ComponentVMOf or is a plain class wrapper
  3. Observable properties — properties exist with correct types; emit
     PropertyChangedMessage when mutated (where applicable)
  4. Commands — present on ScenarioVM; execute() works; can_execute matches docs
  5. Mutation propagation — child VM mutation propagates to parent scenario
  6. Solve trigger semantics — parameterized matrix per spec §3.3
  7. Result VMs are read-only — no mutation methods

Deviation notes
---------------
- CompositeVM wrappers (DecisionsVM, PropertiesVM, etc.) are NOT separate
  classes in the current implementation; the VM tree is managed directly on
  ScenarioVM.  Each of those conceptual "aggregate" types is realised via
  Python lists/tuples on the ScenarioVM, which is documented here.
- AlternativesVM is similarly folded in; alternatives are nested under decisions
  in the scenario model and accessed via ScenarioVM.scenario.alternatives.
- AnalysisVM (M4) is not yet a separate class; chart data is generated by
  guidearch.view.chart_data helper functions.
"""

from __future__ import annotations

from collections.abc import Generator
from pathlib import Path
from typing import Any

import pytest

# ---------------------------------------------------------------------------
# Fixtures and helpers
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).parents[4]
_SAS_JSON = _REPO_ROOT / "spec" / "conformance" / "scenarios" / "sas.json"


@pytest.fixture()
def vm() -> Generator[object, None, None]:
    """Fresh ScenarioVM for each test."""
    from guidearch.viewmodels.scenario_vm import ScenarioVM, make_scenario_vm

    v: ScenarioVM = make_scenario_vm()
    yield v
    v.dispose()


@pytest.fixture()
def vm_sas() -> Generator[object, None, None]:
    """ScenarioVM with SAS scenario pre-loaded."""
    from guidearch.viewmodels.scenario_vm import ScenarioVM, make_scenario_vm

    v: ScenarioVM = make_scenario_vm()
    assert _SAS_JSON.exists(), f"sas.json not found at {_SAS_JSON}"
    v.open_cmd.execute(str(_SAS_JSON))
    yield v
    v.dispose()


def _make_hub_and_dispatcher() -> tuple[Any, Any]:
    """Return a real MessageHub + RxDispatcher for child VM construction tests."""
    from vmx.services.dispatcher import RxDispatcher
    from vmx.services.message_hub import MessageHub

    hub: MessageHub = MessageHub()  # type: ignore[type-arg]
    dispatcher = RxDispatcher.immediate()
    return hub, dispatcher


def _has_property(instance: object, name: str) -> bool:
    klass = type(instance)
    return any(name in base.__dict__ for base in klass.__mro__)


# ---------------------------------------------------------------------------
# §1 — Existence: every VM type is importable from guidearch.viewmodels
# ---------------------------------------------------------------------------


class TestVMExistence:
    """All VM types must be importable from the public package."""

    def test_scenario_vm(self) -> None:
        from guidearch.viewmodels import ScenarioVM

        assert ScenarioVM is not None

    def test_decision_vm(self) -> None:
        from guidearch.viewmodels import DecisionVM

        assert DecisionVM is not None

    def test_alternative_vm(self) -> None:
        from guidearch.viewmodels import AlternativeVM

        assert AlternativeVM is not None

    def test_property_vm(self) -> None:
        from guidearch.viewmodels import PropertyVM

        assert PropertyVM is not None

    def test_coefficient_vm(self) -> None:
        from guidearch.viewmodels import CoefficientVM

        assert CoefficientVM is not None

    def test_threshold_constraint_vm(self) -> None:
        from guidearch.viewmodels import ThresholdConstraintVM

        assert ThresholdConstraintVM is not None

    def test_dependency_constraint_vm(self) -> None:
        from guidearch.viewmodels import DependencyConstraintVM

        assert DependencyConstraintVM is not None

    def test_conflict_constraint_vm(self) -> None:
        from guidearch.viewmodels import ConflictConstraintVM

        assert ConflictConstraintVM is not None

    def test_candidate_vm(self) -> None:
        from guidearch.viewmodels import CandidateVM

        assert CandidateVM is not None

    def test_critical_decision_vm(self) -> None:
        from guidearch.viewmodels import CriticalDecisionVM

        assert CriticalDecisionVM is not None

    def test_critical_constraint_vm(self) -> None:
        from guidearch.viewmodels import CriticalConstraintVM

        assert CriticalConstraintVM is not None

    @pytest.mark.skip(
        reason=(
            "DecisionsVM, PropertiesVM, CoefficientsVM, ConstraintsVM, "
            "ThresholdConstraintsVM, DependencyConstraintsVM, ConflictConstraintsVM, "
            "CandidatesVM, CriticalDecisionsVM, CriticalConstraintsVM, AnalysisVM "
            "are NOT implemented as separate named classes. "
            "The spec §2 composite/aggregate nodes are realised via Python list/tuple "
            "attributes on ScenarioVM (e.g. scenario.decisions, vm.candidates) "
            "and the VMx CompositeVM / AggregateVM builder pattern is not used here. "
            "This is a spec deviation: the Python impl collapses the composite wrappers "
            "into the root ScenarioVM."
        )
    )
    def test_composite_aggregate_wrappers_are_separate_classes(self) -> None:
        # If these were implemented, they would be imported here.
        # e.g.: from guidearch.viewmodels import DecisionsVM, PropertiesVM, ...
        pass


# ---------------------------------------------------------------------------
# §2 — Construction: instantiating produces correct VMx primitive
# ---------------------------------------------------------------------------


class TestConstruction:
    def test_scenario_vm_construction(self) -> None:
        from guidearch.viewmodels.scenario_vm import ScenarioVM, make_scenario_vm

        vm = make_scenario_vm()
        try:
            assert isinstance(vm, ScenarioVM)
            # Initial state: no scenario loaded
            assert vm.scenario is None
            assert vm.candidates == ()
            assert vm.status == "No scenario loaded."
        finally:
            vm.dispose()

    def test_decision_vm_construction(self) -> None:
        from vmx.components.component_vm import ComponentVMOf

        from guidearch.models.decision import DecisionM
        from guidearch.viewmodels import DecisionVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = DecisionM(id="d-test", name="Database")
        vm = DecisionVM(m, hub, dispatcher)
        assert isinstance(vm, ComponentVMOf)
        assert vm.id == "d-test"
        assert vm.decision_name == "Database"

    def test_alternative_vm_construction(self) -> None:
        from vmx.components.component_vm import ComponentVMOf

        from guidearch.models.alternative import AlternativeM
        from guidearch.viewmodels import AlternativeVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = AlternativeM(id="a-test", decision_id="d-test", name="Postgres")
        vm = AlternativeVM(m, hub, dispatcher)
        assert isinstance(vm, ComponentVMOf)
        assert vm.id == "a-test"
        assert vm.decision_id == "d-test"
        assert vm.alt_name == "Postgres"

    def test_property_vm_construction(self) -> None:
        from vmx.components.component_vm import ComponentVMOf

        from guidearch.models.property import PropertyM
        from guidearch.viewmodels import PropertyVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = PropertyM(id="p-test", name="Cost", kind="min", weight=2.0)
        vm = PropertyVM(m, hub, dispatcher)
        assert isinstance(vm, ComponentVMOf)
        assert vm.id == "p-test"
        assert vm.prop_name == "Cost"
        assert vm.kind == "min"
        assert vm.weight == 2.0

    def test_coefficient_vm_construction(self) -> None:
        from vmx.components.component_vm import ComponentVMOf

        from guidearch.models.coefficient import CoefficientM
        from guidearch.models.triangular_fuzzy import TriangularFuzzyM
        from guidearch.viewmodels import CoefficientVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = CoefficientM(
            alternative_id="a-test",
            property_id="p-test",
            value=TriangularFuzzyM(lower=1.0, modal=2.0, upper=3.0),
        )
        vm = CoefficientVM(m, hub, dispatcher)
        assert isinstance(vm, ComponentVMOf)
        assert vm.lower == 1.0
        assert vm.modal == 2.0
        assert vm.upper == 3.0

    def test_threshold_constraint_vm_construction(self) -> None:
        from vmx.components.component_vm import ComponentVMOf

        from guidearch.models.constraint import ThresholdConstraint
        from guidearch.viewmodels import ThresholdConstraintVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = ThresholdConstraint(kind="threshold", property_id="p-test", min=0.5, max=None)
        vm = ThresholdConstraintVM(m, index=0, hub=hub, dispatcher=dispatcher)
        assert isinstance(vm, ComponentVMOf)
        assert vm.constraint_index == 0
        assert vm.property_id == "p-test"
        assert vm.min_value == 0.5
        assert vm.max_value is None

    def test_dependency_constraint_vm_construction(self) -> None:
        from vmx.components.component_vm import ComponentVMOf

        from guidearch.models.constraint import DependencyConstraint
        from guidearch.viewmodels import DependencyConstraintVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = DependencyConstraint(
            kind="dependency", source_alternative_id="a1", target_alternative_id="a2"
        )
        vm = DependencyConstraintVM(m, index=1, hub=hub, dispatcher=dispatcher)
        assert isinstance(vm, ComponentVMOf)
        assert vm.constraint_index == 1
        assert vm.source_alternative_id == "a1"
        assert vm.target_alternative_id == "a2"

    def test_conflict_constraint_vm_construction(self) -> None:
        from vmx.components.component_vm import ComponentVMOf

        from guidearch.models.constraint import ConflictConstraint
        from guidearch.viewmodels import ConflictConstraintVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = ConflictConstraint(kind="conflict", alternative_a_id="a1", alternative_b_id="a2")
        vm = ConflictConstraintVM(m, index=2, hub=hub, dispatcher=dispatcher)
        assert isinstance(vm, ComponentVMOf)
        assert vm.constraint_index == 2
        assert vm.alternative_a_id == "a1"
        assert vm.alternative_b_id == "a2"

    def test_candidate_vm_construction(self) -> None:
        from guidearch.models.candidate import CandidateM
        from guidearch.models.normalized_fuzzy import NormalizedFuzzyM
        from guidearch.models.triangular_fuzzy import TriangularFuzzyM
        from guidearch.viewmodels import CandidateVM

        m = CandidateM(
            alternative_ids=("a1", "a2"),
            triangular_value=TriangularFuzzyM(0.1, 0.5, 0.9),
            normalized_value=NormalizedFuzzyM(0.7, 0.1, 0.2),
            score=0.7,
            rank=0,
        )
        vm = CandidateVM(m)
        assert vm.rank == 0
        assert vm.score == 0.7
        assert vm.alternative_ids == ("a1", "a2")

    def test_critical_decision_vm_construction(self) -> None:
        from guidearch.models.critical_decision import CriticalDecisionM
        from guidearch.models.normalized_fuzzy import NormalizedFuzzyM
        from guidearch.models.triangular_fuzzy import TriangularFuzzyM
        from guidearch.viewmodels import CriticalDecisionVM

        m = CriticalDecisionM(
            decision_id="d1",
            triangular_value=TriangularFuzzyM(0.0, 0.5, 1.0),
            normalized_value=NormalizedFuzzyM(0.5, 0.2, 0.3),
            score=0.5,
            rank=0,
        )
        vm = CriticalDecisionVM(m)
        assert vm.decision_id == "d1"
        assert vm.score == 0.5
        assert vm.rank == 0

    def test_critical_constraint_vm_construction(self) -> None:
        from guidearch.models.critical_constraint import CriticalConstraintM
        from guidearch.viewmodels import CriticalConstraintVM

        m = CriticalConstraintM(
            constraint_index=3,
            kind="threshold",
            eliminated=20,
            total=100,
            redundant=False,
        )
        vm = CriticalConstraintVM(m)
        assert vm.constraint_index == 3
        assert vm.kind == "threshold"
        assert vm.eliminated == 20
        assert vm.total == 100
        assert vm.redundant is False


# ---------------------------------------------------------------------------
# §3 — Observable properties emit PropertyChangedMessage on write
# ---------------------------------------------------------------------------


class TestObservablePropertyChangedEmissions:
    """Verify that mutating properties emits PropertyChangedMessage via hub."""

    def test_decision_vm_name_emits_changed(self) -> None:
        from vmx.messages.property_changed import PropertyChangedMessage

        from guidearch.models.decision import DecisionM
        from guidearch.viewmodels import DecisionVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = DecisionM(id="d1", name="Old Name")
        vm = DecisionVM(m, hub, dispatcher)

        received: list[object] = []
        hub.messages.subscribe(on_next=received.append)

        vm.decision_name = "New Name"

        assert any(isinstance(msg, PropertyChangedMessage) for msg in received)
        assert vm.decision_name == "New Name"

    def test_alternative_vm_decision_id_emits_changed(self) -> None:
        from vmx.messages.property_changed import PropertyChangedMessage

        from guidearch.models.alternative import AlternativeM
        from guidearch.viewmodels import AlternativeVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = AlternativeM(id="a1", decision_id="d1", name="Alt")
        vm = AlternativeVM(m, hub, dispatcher)

        received: list[object] = []
        hub.messages.subscribe(on_next=received.append)

        vm.decision_id = "d2"

        assert any(isinstance(msg, PropertyChangedMessage) for msg in received)
        assert vm.decision_id == "d2"

    def test_property_vm_kind_emits_changed(self) -> None:
        from vmx.messages.property_changed import PropertyChangedMessage

        from guidearch.models.property import PropertyM
        from guidearch.viewmodels import PropertyVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = PropertyM(id="p1", name="Cost", kind="min", weight=1.0)
        vm = PropertyVM(m, hub, dispatcher)

        received: list[object] = []
        hub.messages.subscribe(on_next=received.append)

        vm.kind = "max"

        assert any(isinstance(msg, PropertyChangedMessage) for msg in received)
        assert vm.kind == "max"

    def test_property_vm_weight_emits_changed(self) -> None:
        from vmx.messages.property_changed import PropertyChangedMessage

        from guidearch.models.property import PropertyM
        from guidearch.viewmodels import PropertyVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = PropertyM(id="p1", name="Cost", kind="min", weight=1.0)
        vm = PropertyVM(m, hub, dispatcher)

        received: list[object] = []
        hub.messages.subscribe(on_next=received.append)

        vm.weight = 3.5

        assert any(isinstance(msg, PropertyChangedMessage) for msg in received)
        assert vm.weight == 3.5

    def test_coefficient_vm_lower_emits_changed(self) -> None:
        from vmx.messages.property_changed import PropertyChangedMessage

        from guidearch.models.coefficient import CoefficientM
        from guidearch.models.triangular_fuzzy import TriangularFuzzyM
        from guidearch.viewmodels import CoefficientVM

        hub, dispatcher = _make_hub_and_dispatcher()
        m = CoefficientM(
            alternative_id="a1", property_id="p1", value=TriangularFuzzyM(1.0, 2.0, 3.0)
        )
        vm = CoefficientVM(m, hub, dispatcher)

        received: list[object] = []
        hub.messages.subscribe(on_next=received.append)

        vm.lower = 0.5

        assert any(isinstance(msg, PropertyChangedMessage) for msg in received)
        assert vm.lower == 0.5

    def test_scenario_vm_emits_property_changed_on_open(self) -> None:
        from guidearch.viewmodels.scenario_vm import make_scenario_vm

        vm = make_scenario_vm()
        try:
            props_changed: list[str] = []
            vm.property_changed.subscribe(on_next=props_changed.append)

            vm.open_cmd.execute(str(_SAS_JSON))

            assert "scenario" in props_changed
            assert "candidates" in props_changed
            assert "status" in props_changed
        finally:
            vm.dispose()


# ---------------------------------------------------------------------------
# §4 — Commands: existence, execute() works, can_execute preconditions
# ---------------------------------------------------------------------------


class TestScenarioVMCommands:
    def test_all_commands_exist(self, vm: object) -> None:
        for cmd_name in ("new_cmd", "open_cmd", "save_cmd", "save_as_cmd", "solve_cmd"):
            assert hasattr(vm, cmd_name), f"Missing command: {cmd_name}"

    def test_save_cmd_cannot_execute_when_no_file_path(self, vm: object) -> None:
        """save_cmd.can_execute() is False when file_path is None."""
        assert not vm.save_cmd.can_execute()  # type: ignore[attr-defined]

    def test_solve_cmd_cannot_execute_when_no_scenario(self, vm: object) -> None:
        """solve_cmd.can_execute() is False when scenario is None."""
        assert not vm.solve_cmd.can_execute()  # type: ignore[attr-defined]

    def test_new_cmd_always_enabled(self, vm: object) -> None:
        """new_cmd has no predicate — always enabled."""
        # new_cmd should always execute
        vm.new_cmd.execute()  # type: ignore[attr-defined]
        assert vm.scenario is not None  # type: ignore[attr-defined]

    def test_new_cmd_creates_empty_scenario(self, vm: object) -> None:
        vm.new_cmd.execute()  # type: ignore[attr-defined]
        assert vm.scenario is not None  # type: ignore[attr-defined]
        assert vm.file_path is None  # type: ignore[attr-defined]
        assert vm.is_dirty is False  # type: ignore[attr-defined]

    def test_open_cmd_loads_sas(self, vm: object) -> None:
        vm.open_cmd.execute(str(_SAS_JSON))  # type: ignore[attr-defined]
        assert vm.scenario is not None  # type: ignore[attr-defined]
        assert vm.scenario.name == "SAS"  # type: ignore[attr-defined]

    def test_solve_cmd_enabled_after_open(self, vm_sas: object) -> None:
        assert vm_sas.solve_cmd.can_execute()  # type: ignore[attr-defined]

    def test_save_cmd_disabled_after_open_via_path_no_file(self, vm: object) -> None:
        """After open_cmd the file_path is set, so save_cmd should be enabled."""
        vm.open_cmd.execute(str(_SAS_JSON))  # type: ignore[attr-defined]
        # file_path is set — save should be enabled
        assert vm.save_cmd.can_execute()  # type: ignore[attr-defined]

    def test_save_as_cmd_sets_file_path(self, vm_sas: object, tmp_path: object) -> None:
        from pathlib import Path

        tmp = Path(str(tmp_path)) / "out.json"
        vm_sas.save_as_cmd.execute(str(tmp))  # type: ignore[attr-defined]
        assert vm_sas.file_path == str(tmp)  # type: ignore[attr-defined]
        assert tmp.exists()

    def test_solve_cmd_execute_produces_candidates(self, vm_sas: object) -> None:
        count_before = len(vm_sas.candidates)  # type: ignore[attr-defined]
        vm_sas.solve_cmd.execute()  # type: ignore[attr-defined]
        # Should still have candidates after explicit re-solve
        assert len(vm_sas.candidates) == count_before  # type: ignore[attr-defined]


# ---------------------------------------------------------------------------
# §5 — Mutation propagation (child → parent)
# ---------------------------------------------------------------------------


class TestMutationPropagation:
    def test_update_decision_name_propagates_to_scenario(self, vm_sas: object) -> None:
        """update_decision_name marks dirty and updates scenario.decisions in-place."""
        scenario_before = vm_sas.scenario  # type: ignore[attr-defined]
        first_decision = scenario_before.decisions[0]
        old_name = first_decision.name

        vm_sas.update_decision_name(first_decision.id, "Renamed Decision")  # type: ignore[attr-defined]

        assert vm_sas.scenario is not None  # type: ignore[attr-defined]
        updated = next(d for d in vm_sas.scenario.decisions if d.id == first_decision.id)  # type: ignore[attr-defined]
        assert updated.name == "Renamed Decision"
        assert vm_sas.is_dirty is True  # type: ignore[attr-defined]

        # Cleanup: restore
        vm_sas.update_decision_name(first_decision.id, old_name)  # type: ignore[attr-defined]

    def test_update_property_weight_propagates(self, vm_sas: object) -> None:
        """Changing property weight should propagate to scenario and re-solve."""
        first_prop = vm_sas.scenario.properties[0]  # type: ignore[attr-defined]
        old_weight = first_prop.weight

        vm_sas.update_property(first_prop.id, weight=old_weight * 10.0)  # type: ignore[attr-defined]

        # Scenario updated
        updated_prop = next(
            p
            for p in vm_sas.scenario.properties  # type: ignore[attr-defined]
            if p.id == first_prop.id
        )
        assert updated_prop.weight == pytest.approx(old_weight * 10.0)

    def test_add_decision_updates_scenario(self, vm_sas: object) -> None:
        count_before = len(vm_sas.scenario.decisions)  # type: ignore[attr-defined]
        new_id = vm_sas.add_decision("Test Decision X")  # type: ignore[attr-defined]
        assert len(vm_sas.scenario.decisions) == count_before + 1  # type: ignore[attr-defined]
        assert any(d.id == new_id for d in vm_sas.scenario.decisions)  # type: ignore[attr-defined]

    def test_delete_decision_cascades(self, vm_sas: object) -> None:
        # Add a decision then delete it and verify cascade
        new_id = vm_sas.add_decision("To Delete")  # type: ignore[attr-defined]
        alt_id = vm_sas.add_alternative(new_id, "Alt Under Deleted")  # type: ignore[attr-defined]

        vm_sas.delete_decision(new_id)  # type: ignore[attr-defined]

        assert not any(d.id == new_id for d in vm_sas.scenario.decisions)  # type: ignore[attr-defined]
        assert not any(a.id == alt_id for a in vm_sas.scenario.alternatives)  # type: ignore[attr-defined]


# ---------------------------------------------------------------------------
# §6 — Solve trigger semantics (spec §3.3)
# ---------------------------------------------------------------------------


def _is_dirty_after(vm_sas: object, op: object) -> bool:
    """Return whether is_dirty is True after calling op(vm_sas)."""
    # Reset dirty flag: load fresh — not yet used in parametrized tests
    return False


def _candidates_change_after(vm_sas_factory: object, op: object) -> bool:
    """Helper: return True if op causes a re-solve (candidates count may change)."""
    return False


@pytest.mark.parametrize(
    "description, mutation_fn, should_trigger_solve",
    [
        # ── Should NOT trigger solve ─────────────────────────────────────────
        pytest.param(
            "decision name change does not trigger solve",
            lambda vm: vm.update_decision_name(vm.scenario.decisions[0].id, "X"),
            False,
            id="decision_name_no_solve",
        ),
        pytest.param(
            "scenario name change does not trigger solve",
            lambda vm: vm.update_scenario_name("New Name"),
            False,
            id="scenario_name_no_solve",
        ),
        pytest.param(
            "alternative name change does not trigger solve",
            lambda vm: vm.update_alternative_name(vm.scenario.alternatives[0].id, "Y"),
            False,
            id="alternative_name_no_solve",
        ),
        pytest.param(
            "file_path change (save_as with same content) does not trigger solve",
            lambda vm: None,  # Tested separately — can't easily test without file
            False,
            id="file_path_no_solve",
        ),
        # ── Should trigger solve ─────────────────────────────────────────────
        pytest.param(
            "adding an alternative triggers solve",
            lambda vm: vm.add_alternative(vm.scenario.decisions[0].id, "Trigger Alt"),
            True,
            id="add_alternative_triggers_solve",
        ),
        pytest.param(
            "deleting an alternative triggers solve",
            lambda vm: vm.delete_alternative(vm.scenario.alternatives[-1].id),
            True,
            id="delete_alternative_triggers_solve",
        ),
        pytest.param(
            "adding a decision triggers solve",
            lambda vm: vm.add_decision("Trigger Dec"),
            True,
            id="add_decision_triggers_solve",
        ),
        pytest.param(
            "changing property kind triggers solve",
            lambda vm: vm.update_property(
                vm.scenario.properties[0].id,
                kind="max" if vm.scenario.properties[0].kind == "min" else "min",
            ),
            True,
            id="property_kind_triggers_solve",
        ),
        pytest.param(
            "changing property weight triggers solve",
            lambda vm: vm.update_property(vm.scenario.properties[0].id, weight=999.0),
            True,
            id="property_weight_triggers_solve",
        ),
        pytest.param(
            "adding a property triggers solve",
            lambda vm: vm.add_property("New Prop", "min", 1.0),
            True,
            id="add_property_triggers_solve",
        ),
        pytest.param(
            "updating a coefficient value triggers solve",
            lambda vm: vm.update_coefficient(
                vm.scenario.alternatives[0].id,
                vm.scenario.properties[0].id,
                0.1,
                0.5,
                0.9,
            ),
            True,
            id="coefficient_value_triggers_solve",
        ),
        pytest.param(
            "adding a threshold constraint triggers solve",
            lambda vm: vm.add_threshold_constraint(vm.scenario.properties[0].id, min_val=0.1),
            True,
            id="add_threshold_constraint_triggers_solve",
        ),
        pytest.param(
            "adding a dependency constraint triggers solve",
            lambda vm: (
                vm.add_dependency_constraint(
                    vm.scenario.alternatives[0].id,
                    vm.scenario.alternatives[1].id,
                )
                if len(vm.scenario.alternatives) >= 2
                else None
            ),
            True,
            id="add_dependency_constraint_triggers_solve",
        ),
        pytest.param(
            "adding a conflict constraint triggers solve",
            lambda vm: (
                vm.add_conflict_constraint(
                    vm.scenario.alternatives[0].id,
                    vm.scenario.alternatives[1].id,
                )
                if len(vm.scenario.alternatives) >= 2
                else None
            ),
            True,
            id="add_conflict_constraint_triggers_solve",
        ),
        pytest.param(
            "deleting a constraint triggers solve",
            lambda vm: (
                vm.add_threshold_constraint(vm.scenario.properties[0].id, min_val=0.01)
                or vm.delete_constraint(len(vm.scenario.constraints) - 1)
            ),
            True,
            id="delete_constraint_triggers_solve",
        ),
    ],
)
def test_solve_trigger_matrix(
    description: str,
    mutation_fn: object,
    should_trigger_solve: bool,
) -> None:
    """Parameterized solve-trigger matrix per spec §3.3.

    Strategy: count the number of times _do_solve() is called by monitoring
    property_changed emissions for 'candidates'.  A solve-triggering mutation
    calls _apply_scenario_mutation() which calls _do_solve() synchronously.
    """
    from guidearch.viewmodels.scenario_vm import make_scenario_vm

    vm = make_scenario_vm()
    try:
        assert _SAS_JSON.exists(), f"sas.json not found at {_SAS_JSON}"
        vm.open_cmd.execute(str(_SAS_JSON))

        solve_calls: list[str] = []
        vm.property_changed.subscribe(
            on_next=lambda p: solve_calls.append(p) if p == "candidates" else None
        )

        # Apply the mutation
        mutation_fn(vm)  # type: ignore[operator]

        did_solve = len(solve_calls) > 0

        if description.endswith("does not trigger solve"):
            assert not did_solve, (
                f"Expected NO solve for '{description}', but solve was triggered. "
                f"Candidates change emissions: {solve_calls}"
            )
        else:
            if should_trigger_solve:
                assert did_solve, (
                    f"Expected solve for '{description}', but no solve triggered. "
                    f"Candidates change emissions: {solve_calls}"
                )
    finally:
        vm.dispose()


# ---------------------------------------------------------------------------
# §7 — Result VMs are read-only
# ---------------------------------------------------------------------------


class TestResultVMsAreReadOnly:
    """CandidateVM, CriticalDecisionVM, CriticalConstraintVM must expose no
    mutation methods — no setters, no commands."""

    def _check_no_setters(self, vm_instance: object, public_props: list[str]) -> None:
        """Assert that no public property has a setter."""
        klass = type(vm_instance)
        for name in public_props:
            attr = next(
                (base.__dict__.get(name) for base in klass.__mro__ if name in base.__dict__),
                None,
            )
            if isinstance(attr, property):
                assert attr.fset is None, (
                    f"{klass.__name__}.{name} has a setter — result VMs must be read-only"
                )

    def test_candidate_vm_no_setters(self) -> None:
        from guidearch.models.candidate import CandidateM
        from guidearch.models.normalized_fuzzy import NormalizedFuzzyM
        from guidearch.models.triangular_fuzzy import TriangularFuzzyM
        from guidearch.viewmodels import CandidateVM

        m = CandidateM(
            alternative_ids=("a1",),
            triangular_value=TriangularFuzzyM(0.1, 0.5, 0.9),
            normalized_value=NormalizedFuzzyM(0.7, 0.1, 0.2),
            score=0.7,
            rank=0,
        )
        vm = CandidateVM(m)
        self._check_no_setters(vm, ["rank", "score", "alternative_ids"])

    def test_candidate_vm_no_commands(self) -> None:
        from guidearch.models.candidate import CandidateM
        from guidearch.models.normalized_fuzzy import NormalizedFuzzyM
        from guidearch.models.triangular_fuzzy import TriangularFuzzyM
        from guidearch.viewmodels import CandidateVM

        m = CandidateM(
            alternative_ids=("a1",),
            triangular_value=TriangularFuzzyM(0.1, 0.5, 0.9),
            normalized_value=NormalizedFuzzyM(0.7, 0.1, 0.2),
            score=0.7,
            rank=0,
        )
        vm = CandidateVM(m)
        # Must not have any *_cmd attributes
        assert not any(attr.endswith("_cmd") for attr in dir(vm)), (
            "CandidateVM must not have command attributes"
        )

    def test_critical_decision_vm_no_setters(self) -> None:
        from guidearch.models.critical_decision import CriticalDecisionM
        from guidearch.models.normalized_fuzzy import NormalizedFuzzyM
        from guidearch.models.triangular_fuzzy import TriangularFuzzyM
        from guidearch.viewmodels import CriticalDecisionVM

        m = CriticalDecisionM(
            decision_id="d1",
            triangular_value=TriangularFuzzyM(0.0, 0.5, 1.0),
            normalized_value=NormalizedFuzzyM(0.5, 0.2, 0.3),
            score=0.5,
            rank=0,
        )
        vm = CriticalDecisionVM(m)
        self._check_no_setters(vm, ["decision_id", "score", "rank"])

    def test_critical_decision_vm_no_commands(self) -> None:
        from guidearch.models.critical_decision import CriticalDecisionM
        from guidearch.models.normalized_fuzzy import NormalizedFuzzyM
        from guidearch.models.triangular_fuzzy import TriangularFuzzyM
        from guidearch.viewmodels import CriticalDecisionVM

        m = CriticalDecisionM(
            decision_id="d1",
            triangular_value=TriangularFuzzyM(0.0, 0.5, 1.0),
            normalized_value=NormalizedFuzzyM(0.5, 0.2, 0.3),
            score=0.5,
            rank=0,
        )
        vm = CriticalDecisionVM(m)
        assert not any(attr.endswith("_cmd") for attr in dir(vm)), (
            "CriticalDecisionVM must not have command attributes"
        )

    def test_critical_constraint_vm_no_setters(self) -> None:
        from guidearch.models.critical_constraint import CriticalConstraintM
        from guidearch.viewmodels import CriticalConstraintVM

        m = CriticalConstraintM(
            constraint_index=0,
            kind="threshold",
            eliminated=10,
            total=50,
            redundant=True,
        )
        vm = CriticalConstraintVM(m)
        self._check_no_setters(vm, ["constraint_index", "kind", "eliminated", "total", "redundant"])

    def test_critical_constraint_vm_no_commands(self) -> None:
        from guidearch.models.critical_constraint import CriticalConstraintM
        from guidearch.viewmodels import CriticalConstraintVM

        m = CriticalConstraintM(
            constraint_index=0,
            kind="threshold",
            eliminated=10,
            total=50,
            redundant=True,
        )
        vm = CriticalConstraintVM(m)
        assert not any(attr.endswith("_cmd") for attr in dir(vm)), (
            "CriticalConstraintVM must not have command attributes"
        )


# ---------------------------------------------------------------------------
# Extra: scenario_vm.is_dirty state machine
# ---------------------------------------------------------------------------


class TestDirtyFlagStateMachine:
    def test_starts_not_dirty(self, vm: object) -> None:
        assert vm.is_dirty is False  # type: ignore[attr-defined]

    def test_open_cmd_clears_dirty(self, vm: object) -> None:
        vm.open_cmd.execute(str(_SAS_JSON))  # type: ignore[attr-defined]
        assert vm.is_dirty is False  # type: ignore[attr-defined]

    def test_mutation_marks_dirty(self, vm_sas: object) -> None:
        assert vm_sas.is_dirty is False  # type: ignore[attr-defined]
        d_id = vm_sas.scenario.decisions[0].id  # type: ignore[attr-defined]
        vm_sas.update_decision_name(d_id, "Dirty!")  # type: ignore[attr-defined]
        assert vm_sas.is_dirty is True  # type: ignore[attr-defined]

    def test_new_cmd_clears_dirty(self, vm_sas: object) -> None:
        d_id = vm_sas.scenario.decisions[0].id  # type: ignore[attr-defined]
        vm_sas.update_decision_name(d_id, "Dirty!")  # type: ignore[attr-defined]
        assert vm_sas.is_dirty is True  # type: ignore[attr-defined]
        vm_sas.new_cmd.execute()  # type: ignore[attr-defined]
        assert vm_sas.is_dirty is False  # type: ignore[attr-defined]


# ---------------------------------------------------------------------------
# Extra: ScenarioVM warning / error handling
# ---------------------------------------------------------------------------


class TestScenarioVMErrorHandling:
    def test_open_bad_path_emits_warning(self, vm: object) -> None:
        vm.open_cmd.execute("/does/not/exist.json")  # type: ignore[attr-defined]
        assert len(vm.warnings) > 0  # type: ignore[attr-defined]
        assert vm.scenario is None  # type: ignore[attr-defined]

    def test_open_bad_path_does_not_mutate_loaded_scenario(self, vm_sas: object) -> None:
        name_before = vm_sas.scenario.name  # type: ignore[attr-defined]
        vm_sas.open_cmd.execute("/does/not/exist.json")  # type: ignore[attr-defined]
        assert vm_sas.scenario.name == name_before  # type: ignore[attr-defined]

    def test_delete_decision_unknown_id_raises(self, vm_sas: object) -> None:
        with pytest.raises(ValueError, match="not found"):
            vm_sas.delete_decision("not-a-real-id")  # type: ignore[attr-defined]

    def test_delete_alternative_unknown_id_raises(self, vm_sas: object) -> None:
        with pytest.raises(ValueError, match="not found"):
            vm_sas.delete_alternative("not-a-real-id")  # type: ignore[attr-defined]

    def test_delete_property_unknown_id_raises(self, vm_sas: object) -> None:
        with pytest.raises(ValueError, match="not found"):
            vm_sas.delete_property("not-a-real-id")  # type: ignore[attr-defined]

    def test_delete_constraint_out_of_range_raises(self, vm_sas: object) -> None:
        with pytest.raises(ValueError, match="out of range"):
            vm_sas.delete_constraint(9999)  # type: ignore[attr-defined]
